### ISSUE TITLE
Code path of MoSLoRA

### ISSUE THREAD

**Issue by vanity1129** [wutaiqiang/MoSLoRA#1]
Can you provide a specific path to quickly locate the location of MoSLoRA

**Comment by wutaiqiang** [comment]
https://github.com/wutaiqiang/MoSLoRA/blob/bba79b5491742df44e740e7348a265a0954da903/visual_instruction_tuning/peft/tuners/lora/layer.py#L577

set "self.lora_use_mixer==True" to start moslora

**Comment by wutaiqiang** [comment]
or you can install this github:

https://github.com/wutaiqiang/peft

to replace the official peft. Just set use_moslora=True in LoRA config and you can start it easily.
