### ISSUE TITLE
How to see the evalution results?

### ISSUE THREAD

**Issue by gf457832386** [wutaiqiang/MoSLoRA#4]
I have run the train_moslora.py, where can I find the final acc of model?  I only see it printed in the process. Thank you.

**Comment by wutaiqiang** [comment]
Typically, you can locate the “test finished” and the ACC result for this dataset is 2-3 lines before this.

One example:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/1869d185-1a13-4de7-8206-793bc542f93f">

The result is 87.65

**Comment by gf457832386** [comment]
Thanks I canculate it by search the"true" and "false" in the json

**Comment by wutaiqiang** [comment]
It also works
